### ISSUE TITLE
librosa doesn't work

### ISSUE THREAD

**Issue by songhe17** [arnavlavan/Rhythmic-Complexity-from-Audio#1]
I install the librosa but it does not work. Here is the error:
`loading audio file...
/home/ubuntu/.local/lib/python3.6/site-packages/librosa/core/audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/librosa/core/audio.py", line 146, in load
    with sf.SoundFile(path) as sf_desc:
  File "/home/ubuntu/.local/lib/python3.6/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'data/mp3/3.mp3': File contains data in an unknown format.

`

**Comment by amiravni** [comment]
It could be that you don't have "ffmpeg" installed
Try it and let us know if it solves the issue

**Comment by songhe17** [comment]
That works! BTW I am wondering if we want to use your code in our research paper, how could we cite your work?

**Comment by arnavlavan** [comment]
Hi :), We've added citation to the readme file, you are welcome to use the code and cite us. Please let us know once your work is published, and all the best :)
